server:
  port: 0
  servlet:
    context-path: /error
spring:
  profiles:
    active: local
  application:
    version: error
  datasource:
    username: error
    password: error
    url: error
    driver-class-name: com.mysql.cj.jdbc.Driver