server:
  port: 55501
  servlet:
    context-path: /kechang
spring:
  profiles:
    active: local
  application:
    version: t1.0.0
  datasource:
    username: root
    password: Root3)))
    url: jdbc:mysql://localhost:3306/kechang?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC